# Generated by Django 4.2.5 on 2023-09-16 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=50)),
                ('middle_name', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('surname', models.CharField(default=' ', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=' ', max_length=1)),
                ('phone_number', models.CharField(default=' ', max_length=15)),
                ('level_of_education', models.CharField(default=' ', max_length=50)),
                ('school_currently_teaching', models.CharField(default=' ', max_length=100)),
                ('council_currently_working', models.CharField(default=' ', max_length=100)),
                ('district_council_preference', models.CharField(default=' ', max_length=100)),
                ('first_subject_major', models.CharField(default=' ', max_length=50)),
                ('second_subject', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('form_status', models.IntegerField(default='0')),
                ('profile_edited', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
